- name: Synchroniser le répertoire mlruns
  synchronize:
    src: ../../modele_ML/mlruns/
    dest: /home/ubuntu/mlruns/
    rsync_opts:
      - "--archive"
      - "--delete"

- name: Supprimer l'ancien conteneur (si existant)
  command: docker rm -f ml-api-container
  ignore_errors: yes

- name: Déployer le conteneur de l'API
  command: >
    docker run -d --name ml-api-container -p 5000:5000
    -v /home/ubuntu/mlruns:/app/mlruns
    app-api
